# webservice/nginx.conf (TESZT CÉLRA: HTTP BLOKK BEÉPÍTÉSE)

events {
    # Alapértelmezett érték: 1024 kapcsolat worker process-enként
    worker_connections 1024; 
}

http {
    # Alapértelmezett MIME típusok
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # NGINX figyeli a 80-as portot
        listen 80;
        index index.php index.html;
        server_name _;
        root /var/www/html; # A weboldal gyökérkönyvtára

        # Minden lekérést a root könyvtárból szolgál ki
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # PHP kérések feldolgozása
        location ~ \.php$ {
            # FastCGI pass a PHP-FPM-hez (ugyanabban a konténerben, localhost:9000-en)
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;

            expires off;
        }

        # .htaccess fájlok tiltása (biztonsági okokból)
        location ~ /\.ht {
            deny all;
        }
    }
}